### ISSUE TITLE
Problems on version 2.0.0 and composer

### ISSUE THREAD

**Issue by prsolucoes** [vova07/yii2-imperavi-widget#109] opened 2017-12-04 22:33 UTC
Hi,

I have a problem when update to version 2, composer write an empty folder inside vova07:

![image](https://user-images.githubusercontent.com/395096/33579859-4d98313a-d932-11e7-8bed-145d55d8fe41.png)

Is only with me?

**Comment by vova07** [comment] 2017-12-05 09:15
Hi @prsolucoes ,
Just tested it on fresh `yii2-basic` project. 
It works for me as expected.
Can you remove the entire folder `vova07` from your `vendor` and the widget dependency from `composer.json` and run this command after that:
`composer require --prefer-dist vova07/yii2-imperavi-widget`

**Comment by prsolucoes** [comment] 2017-12-05 20:28
Hi,

1 - I have removed the vendor path, and everything was installed with success, butt.... you need explain/document that GetAction is GetImagesAction now. Your code example is wrong too:
https://github.com/vova07/yii2-imperavi-widget/blob/master/src/actions/GetImagesAction.php#L30

2- After update the editor still not showing, see:
![image](https://user-images.githubusercontent.com/395096/33629069-ec44d7d6-d9e9-11e7-842a-d08762540224.png)

Can you help me?

**Comment by vova07** [comment] 2017-12-06 16:53
Hi @prsolucoes can you please provide your widget setup you use in your app?

**Comment by prsolucoes** [comment] 2017-12-06 17:13
Hi,

My controller:

```php
public function actions()
    {
        return [
            'get-images' => [
                'class' => GetImagesAction::className(),
                'url' => Url::to('/uploads/general'),
                'path' => Yii::getAlias('@root/uploads/general'),
            ],
            'upload-image' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => Url::to('/uploads/general'),
                'path' => Yii::getAlias('@root/uploads/general'),
            ],
        ];
    }
```

My widget:

```php
<?= $form->field($model, 'content')->widget(
	Widget::className(),
	[
		'settings' => [
			'plugins' => ['imagemanager', 'fullscreen', 'fontcolor', 'video'],
			'minHeight' => 200,
			'imageUpload' => Yii::$app->urlManager->createUrl(['/content/upload-image']),
			'imageManagerJson' => Url::to(['/content/get-images']),
		]
	]
) ?>
```

**Comment by vova07** [comment] 2017-12-08 08:49
@prsolucoes I've tested you code, it works fine for me.
I think the problem is with your `jQuery` version.  (Main is `v3.2.1`)
Can you please try to upgrade your `jQuery` library to version `3.*`, and test it again?!

**Comment by prsolucoes** [comment] 2017-12-08 13:53
Hi,

Im using version 3.2.1, see:

![image](https://user-images.githubusercontent.com/395096/33768718-549b53e8-dc0e-11e7-9069-76bfeeded99a.png)

**Comment by vova07** [comment] 2017-12-09 18:20
@prsolucoes I'm not sure I'm able to help you without any real code.
By real code I mean some kind of integral system because I'm sure that you have some conflicts.
As I said on my empty project your code works without problems.
I suggest you to try your code on some empty project and in case it will work, then you probably have some scripts that have conflicts.
Please provide some feedback after you'll do that.
Thanks!

**Comment by vova07** [comment] 2018-01-20 17:33
I'm going to close this issue.
If you think it's still actual, please feel free to re-open it any time.

**Closed by vova07** 2018-01-20 17:33 UTC
